### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by tsaavik** [cpriest/multitail-vanheusden#1]
Is there a cool way to use this within multitail, or do you just run it as a command with a pipe?

**Comment by cpriest** [comment]
Yeah it is a pretty good tool, it's available for RHEL and probably many other distro's as an RPM, once installed it has docs via man multitail.  This is my own upstream fork of the original project.

**Comment by tsaavik** [comment]
I was refering to the specific file:
https://github.com/cpriest/multitail-vanheusden/blob/master/convert-geoip.pl

It appears you committed that file and it was pulled into upstream at some point.
There does not appear to be any docs on how to use it, or how to pull in custom plugins/filters.

**Comment by cpriest** [comment]
Ahh, I see.

No, this isn't my code, it's the code for multi-tail which I just put 
into my own repo, I had planned to work on it but have not yet done so.
