### ISSUE TITLE
Support for colors from the log file.

### ISSUE THREAD

**Issue by SamMousa** [cpriest/multitail-vanheusden#2]
Sometimes the log file itself has control characters for colorizing the lines.
Would it be possible to add support for that kind of colored output?

**Comment by maiermic** [comment]
You can use the option

> **-cT terminalmode**
> Interpret terminal codes. Only ANSI supported at this time.

Create a log file example:

```bash
RED="\033[1;31m" YELLOW="\033[1;33m" GREEN="\033[1;32m" NC="\033[0m" \
  bash -c 'echo -e "${RED}red${NC} ${YELLOW}yellow${NC} ${GREEN}green${NC}"' \
    > tmp.log
```

Show log file:

```bash
multitail -cT ANSI tmp.log
```

Should show something like this
![screenshot](https://user-images.githubusercontent.com/8530117/125200184-0ef0b980-e26a-11eb-9244-0b682907e850.png)

Note: Use `-CT ANSI` to colorize (interpret terminal codes in) all files. `-cT ANSI` is only applied to the next file.

---

Tested with multitail version 6.5.0

**Comment by maiermic** [comment]
I just realised that the rest of a line is not shown in "scroll back" view after a color code. Create a log file example:

```bash
RED="\033[1;31m" YELLOW="\033[1;33m" GREEN="\033[1;32m" NC="\033[0m" \
  bash -c 'echo -e "start ${RED}red${NC} ${YELLOW}yellow${NC} ${GREEN}green${NC} end\nnext line"' \
    > tmp.log
```

Show log file

```bash
multitail -CT ANSI tmp.log
```

and open "scroll back" view by pressing `b` and you should see

![screenshot](https://user-images.githubusercontent.com/8530117/125200983-8b38cc00-e26d-11eb-805f-2d80fa6be0e2.png)

Lines are shown regularly if terminal codes are not interpreted:

```bash
multitail tmp.log
```

![screenshot2](https://user-images.githubusercontent.com/8530117/125201229-71e44f80-e26e-11eb-8888-a2df364ea4f6.png)


@cpriest Is this behaviour intentional?

**Comment by cpriest** [comment]
I was very confused about this.  This isn't my project (multi-tail), I just forked a copy of it back in the day.  You'll want to go post this to the original owner.  I did a quick search and he may have vaporized.  His site isn't even up any more.

But it was vanheusden.com.

**Comment by maiermic** [comment]
@cpriest Thanks for your response. Where is the source code from? Was it available on vanheusden.com? There is no repository of multitail on the authors Github page https://github.com/folkertvanheusden?tab=repositories

**Comment by cpriest** [comment]
Yeah, I really don't recall where I got it from.  I'm surprised I imported it if it wasn't forked from github.com  

I may have planned to make some changes but never got around to it.  A quick search did not find the original author of multi-tail, I'm not sure what happened to him.

**Comment by maiermic** [comment]
According to https://www.vanheusden.com/multitail/

> Hi,
> 
> I'm looking for someone to take over maintenance of multitail.
> 
> Please send an e-mail to mail@vanheusden.com if you like to do so.
> 
> Please note: the code grew organically so might be "interesting" or "difficult" to read.
> For now, check [this github repo](https://github.com/halturin/multitail) to retrieve the source-code.

**Comment by maiermic** [comment]
FYI https://github.com/halturin/multitail/issues/1
